version: "2"
services:
  tic_tac:
    container_name: server
    restart: always
    build: .
    ports:
      - "5000:5001"
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
